backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'img/pics/'
show_preview_links: false
collections:
  - name: 'posts'
    label: 'Journal'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Photo d’en-tête', name: 'picture', widget: 'image' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Durée', name: 'duration', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
